import { mkdir, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { env } from '@platform/config';
import { logger } from '@platform/logger';

/**
 * The compose-side Traefik (infra/compose/traefik/traefik.yml) only
 * auto-requests an ACME cert for routers whose rule is a literal `Host()` —
 * it can't extract a domain from a `HostRegexp()` rule to request a cert
 * against, so a single generic regex router (tenant-app-admin-subdomains.yml)
 * never actually gets a cert for a *new* tenant, even though it does route
 * traffic once a cert exists some other way. `app.acme.techhanker.com`
 * worked because its cert was issued years ago by a since-deleted
 * acme-only Host() router and is still cached in acme.json — nothing
 * regenerates it for glass/globex or any tenant after acme.
 *
 * This writes one small dynamic-config file per tenant, each with literal
 * Host() routers for app.{slug} and admin.{slug}, so Traefik's file
 * provider (watch: true) picks it up and requests a real cert on next
 * reload — no manual step, no Traefik restart. Requires the k8s
 * tenant-provisioner pod to have TRAEFIK_DYNAMIC_DIR hostPath-mounted to
 * the same directory the compose Traefik reads
 * (infra/compose/traefik/dynamic/) — see deployment.yaml.
 */
export async function ensureTenantTraefikRouter(slug: string): Promise<void> {
  const dir = env.TRAEFIK_DYNAMIC_DIR;
  const domain = env.TENANT_BASE_DOMAIN;
  if (!dir || !domain) {
    logger.warn(
      { slug },
      'TRAEFIK_DYNAMIC_DIR/TENANT_BASE_DOMAIN not set, skipping tenant Traefik router',
    );
    return;
  }

  const contents = `# Generated by ensureTenantTraefikRouter for tenant "${slug}" — do not hand-edit,
# re-provisioning regenerates this file. See traefik-router.ts for why this
# exists (literal Host() rules are required for on-demand ACME certs).
http:
  routers:
    app-${slug}-tenant:
      rule: "Host(\`app.${slug}.${domain}\`)"
      service: k8s-ingress
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      priority: 15

    admin-${slug}-tenant:
      rule: "Host(\`admin.${slug}.${domain}\`)"
      service: web-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      priority: 15
`;

  await mkdir(dir, { recursive: true });
  const target = join(dir, `tenant-${slug}.yml`);
  const tmp = `${target}.tmp-${String(process.pid)}`;
  await writeFile(tmp, contents, 'utf8');
  await rename(tmp, target);
  logger.info({ slug, target }, 'Wrote tenant Traefik router');
}
