platform:
  domain: "lvh.me"

web:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

workers:
  replicaCount: 1
  autoscaling:
    enabled: false

appdb:
  primary:
    persistence:
      size: 2Gi

redis:
  master:
    persistence:
      size: 1Gi

keycloak:
  replicaCount: 1
